server:
  port: 7999

spring:
  application:
    name: proxy-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/

zuul:
  prefix: /api
  routes:
    simple:
      path: /simple/**
      serviceId: simple
      sensitiveHeaders: